spring.data.rest.base-path=/api
server.address=0.0.0.0
cors.allowed-origins=http://localhost:4200,http://192.168.178.80:4200,https://ngstocks.com

# OpenAPI/Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none

# MariaDB Database configuration
spring.datasource.url=jdbc:mariadb://192.168.178.31:3306/StocksDB
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=stocksdb
spring.datasource.password=stocksdb
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

# Scheduler Configuration
# Updater Service (Daily at 6:00 AM)
updater.schedule.cron=0 0 6 * * ?
updater.schedule.zone=Europe/Berlin

