
GET https://www.onvista.de/aktien/finder?cols=instrument,instrument.wkn,company.branch.name,company.nameCountry,quote.last,quote.performancePct,doubleValues.perfW52,doubleValues.cnDivYieldM1,doubleValues.cnMarketCapM1&idContinentCompany=258&cnMarketCapM1Range=10264462758.333334;104812662750
Accept: application/json

###

GET https://www.onvista.de/aktien/finder?idBranch=1
Accept: application/json

###

POST http://192.168.178.31:8086/write?db=mydb
Accept: */*
Content-Type: application/octet-stream

< C:\Dev\__GIT\jonesserver\data\body.txt


###
POST https://aktienkatalog.de/api/convert-ticker-isin-wkn?type=isin&search=GB00B1YW4409
Accept: application/json
Content-Type: application/x-www-form-urlencoded

type=isin&search=GB00B1YW4409

###
GET https://aktienkatalog.de/api-docs

###
GET https://api.frankfurter.dev/v1/latest